name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the workflow when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ensure the Node.js version matches your project

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Ensure this is the correct build script

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
        publish_dir: ./build  # Path to the build
